/* data.js — Load dashboard data from the JSON file generated by the Python pipeline */
let cached = null;

export async function loadData() {
  if (cached) return cached;
  try {
    const resp = await fetch('/dashboard_data.json');
    cached = await resp.json();
    return cached;
  } catch (e) {
    console.error('Failed to load dashboard data:', e);
    return null;
  }
}

export function getData() { return cached; }

export function fmt(v, d = 2) {
  if (v == null || v === undefined) return '-';
  if (typeof v !== 'number') return String(v);
  return v.toFixed(d);
}

export function phaseLabel(phases, id) {
  if (!phases || !id) return 'P' + id;
  const p = phases.find(x => x.phase_id === id);
  return p ? 'P' + p.phase_id + ' ' + (p.phase_label || '').substring(0, 40) : 'P' + id;
}

export function phaseColor(id) {
  const colors = ['#e94560','#f7b733','#fc5c65','#3c6382','#38ada9','#e77f67','#a29bfe','#fd79a8','#00cec9','#fdcb6e'];
  return colors[(id - 1) % colors.length] || '#888';
}