import { fmt } from '../data';
export default function Signals({ data }) {
  const sg = data.sg || []; const sp = data.sp || [];
  return (
    <>
      <h2>🎯 Trading Signals</h2>
      <p>Generated by the probabilistic signal engine: Dirichlet(1,1,1) Bayesian posteriors + Kelly/vol-target sizing + ATR-based stops. Each signal is scored against the Prediction Scorecard (P1) which tracks hit-rate and edge-decay. Stale patterns are auto-flagged.</p>

      <h3>📋 Live Signals</h3>
      {sg.length ? sg.map((s, i) => {
        const dir = (s.direction || '').toLowerCase(); const isU = dir === 'up';
        return <div key={i} className={`signal ${isU ? 'up' : 'down'}`}>
          <div className="h">{s.stream?.replace('_session', '')} / P{s.phase_id} / {s.day_archetype || '-'} / {s.current_window} → {s.next_window}</div>
          <div className="a"><span className={`badge ${isU ? 'up' : 'down'}`}>{s.direction} {isU ? fmt(s.p_up, 0) : fmt(s.p_down, 0)}%</span></div>
          <div className="m">Entry ${fmt(s.entry_price)} / SL ${fmt(s.stop_price)} / TP ${fmt(s.target_price)}{s.final_position_fraction ? ` / Size ${Math.round(s.final_position_fraction * 100)}% equity` : ''}</div>
        </div>;
      }) : <div className="note">No signals for current phase/window. Phase 10 sample is small — patterns from the Cross-Phase tab may help.</div>}

      <h3>📊 Strongest Playbook Patterns</h3>
      {sp.length ? <table><thead><tr><th>Stream</th><th>Phase</th><th>Day Type</th><th>Window→Next</th><th>n</th><th>UP%</th><th>DOWN%</th><th>Edge</th></tr></thead>
        <tbody>{sp.slice(0, 25).map((s, i) =>
          <tr key={i}><td>{s.stream?.replace('_session', '')}</td><td>{(s.phase_label || '').substring(0, 18)}</td><td>{s.day_archetype}</td><td>{s.current_window}→{s.top_next_window}</td>
            <td>{s.n_observations}</td><td>{fmt(s.pct_up_next, 1)}</td><td>{fmt(s.pct_down_next, 1)}</td>
            <td>{s.low_confidence_flag ? <span className="badge low">LOW</span> : '—'}</td>
          </tr>
        )}</tbody>
      </table> : <div className="note">No strong patterns. Run pipeline with more data.</div>}

      <div className="note good"><strong>How to read a signal:</strong> "IF day type = X AND current window = Y THEN next window Z goes UP/DOWN with historical probability. Entry at Z's open. SL/TP = ATR × magnitude tier multiplier. Size = min(Kelly fraction, vol-target fraction) × DD multiplier. <span className="badge low">LOW-CONFIDENCE</span> = n&lt;5 — reduce size or skip."</div>
    </>
  );
}